Digipost\Signature\API\XML\Thirdparty\XMLdSig\DSAKeyValueType:
    properties:
        p:
            expose: true
            access_type: public_method
            serialized_name: P
            xml_element:
                namespace: 'http://www.w3.org/2000/09/xmldsig#'
            accessor:
                getter: getP
                setter: setP
            type: Digipost\Signature\API\XML\CustomBase64BinaryType
        q:
            expose: true
            access_type: public_method
            serialized_name: Q
            xml_element:
                namespace: 'http://www.w3.org/2000/09/xmldsig#'
            accessor:
                getter: getQ
                setter: setQ
            type: Digipost\Signature\API\XML\CustomBase64BinaryType
        g:
            expose: true
            access_type: public_method
            serialized_name: G
            xml_element:
                namespace: 'http://www.w3.org/2000/09/xmldsig#'
            accessor:
                getter: getG
                setter: setG
            type: Digipost\Signature\API\XML\CustomBase64BinaryType
        'y':
            expose: true
            access_type: public_method
            serialized_name: 'Y'
            xml_element:
                namespace: 'http://www.w3.org/2000/09/xmldsig#'
            accessor:
                getter: getY
                setter: setY
            type: Digipost\Signature\API\XML\CustomBase64BinaryType
        j:
            expose: true
            access_type: public_method
            serialized_name: J
            xml_element:
                namespace: 'http://www.w3.org/2000/09/xmldsig#'
            accessor:
                getter: getJ
                setter: setJ
            type: Digipost\Signature\API\XML\CustomBase64BinaryType
        seed:
            expose: true
            access_type: public_method
            serialized_name: Seed
            xml_element:
                namespace: 'http://www.w3.org/2000/09/xmldsig#'
            accessor:
                getter: getSeed
                setter: setSeed
            type: Digipost\Signature\API\XML\CustomBase64BinaryType
        pgenCounter:
            expose: true
            access_type: public_method
            serialized_name: PgenCounter
            xml_element:
                namespace: 'http://www.w3.org/2000/09/xmldsig#'
            accessor:
                getter: getPgenCounter
                setter: setPgenCounter
            type: Digipost\Signature\API\XML\CustomBase64BinaryType
