Digipost\Signature\API\XML\Thirdparty\XMLdSig\KeyValueType:
    properties:
        dSAKeyValue:
            expose: true
            access_type: public_method
            serialized_name: DSAKeyValue
            xml_element:
                namespace: 'http://www.w3.org/2000/09/xmldsig#'
            accessor:
                getter: getDSAKeyValue
                setter: setDSAKeyValue
            type: Digipost\Signature\API\XML\Thirdparty\XMLdSig\DSAKeyValue
        rSAKeyValue:
            expose: true
            access_type: public_method
            serialized_name: RSAKeyValue
            xml_element:
                namespace: 'http://www.w3.org/2000/09/xmldsig#'
            accessor:
                getter: getRSAKeyValue
                setter: setRSAKeyValue
            type: Digipost\Signature\API\XML\Thirdparty\XMLdSig\RSAKeyValue
