Digipost\Signature\API\XML\Thirdparty\XMLdSig\SignaturePropertiesType:
    properties:
        id:
            expose: true
            access_type: public_method
            serialized_name: Id
            accessor:
                getter: getId
                setter: setId
            xml_attribute: true
            type: string
        signatureProperty:
            expose: true
            access_type: public_method
            serialized_name: SignatureProperty
            accessor:
                getter: getSignatureProperty
                setter: setSignatureProperty
            xml_list:
                inline: true
                entry_name: SignatureProperty
                namespace: 'http://www.w3.org/2000/09/xmldsig#'
            type: array<Digipost\Signature\API\XML\Thirdparty\XMLdSig\SignatureProperty>
