Digipost\Signature\API\XML\Thirdparty\XMLdSig\SignaturePropertyType:
    properties:
        target:
            expose: true
            access_type: public_method
            serialized_name: Target
            accessor:
                getter: getTarget
                setter: setTarget
            xml_attribute: true
            type: string
        id:
            expose: true
            access_type: public_method
            serialized_name: Id
            accessor:
                getter: getId
                setter: setId
            xml_attribute: true
            type: string
