Digipost\Signature\API\XML\Thirdparty\XMLdSig\TransformsType:
    properties:
        transform:
            expose: true
            access_type: public_method
            serialized_name: Transform
            accessor:
                getter: getTransform
                setter: setTransform
            xml_list:
                inline: true
                entry_name: Transform
                namespace: 'http://www.w3.org/2000/09/xmldsig#'
            type: array<Digipost\Signature\API\XML\Thirdparty\XMLdSig\Transform>
