Digipost\Signature\API\XML\Thirdparty\XAdES\CRLIdentifierType:
    properties:
        uRI:
            expose: true
            access_type: public_method
            serialized_name: URI
            accessor:
                getter: getURI
                setter: setURI
            xml_attribute: true
            type: string
        issuer:
            expose: true
            access_type: public_method
            serialized_name: Issuer
            xml_element:
                namespace: 'http://uri.etsi.org/01903/v1.3.2#'
            accessor:
                getter: getIssuer
                setter: setIssuer
            type: string
        issueTime:
            expose: true
            access_type: public_method
            serialized_name: IssueTime
            xml_element:
                namespace: 'http://uri.etsi.org/01903/v1.3.2#'
            accessor:
                getter: getIssueTime
                setter: setIssueTime
            type: GoetasWebservices\Xsd\XsdToPhp\XMLSchema\DateTime
        number:
            expose: true
            access_type: public_method
            serialized_name: Number
            xml_element:
                namespace: 'http://uri.etsi.org/01903/v1.3.2#'
            accessor:
                getter: getNumber
                setter: setNumber
            type: integer
