Digipost\Signature\API\XML\Thirdparty\XAdES\NoticeReferenceType:
    properties:
        organization:
            expose: true
            access_type: public_method
            serialized_name: Organization
            xml_element:
                namespace: 'http://uri.etsi.org/01903/v1.3.2#'
            accessor:
                getter: getOrganization
                setter: setOrganization
            type: string
        noticeNumbers:
            expose: true
            access_type: public_method
            serialized_name: NoticeNumbers
            accessor:
                getter: getNoticeNumbers
                setter: setNoticeNumbers
            type: array<integer>
            xml_list:
                inline: false
                entry_name: int
                skip_when_empty: false
                namespace: 'http://uri.etsi.org/01903/v1.3.2#'
