Digipost\Signature\API\XML\Thirdparty\XAdES\QualifyingPropertiesReferenceType:
    properties:
        uRI:
            expose: true
            access_type: public_method
            serialized_name: URI
            accessor:
                getter: getURI
                setter: setURI
            xml_attribute: true
            type: string
        id:
            expose: true
            access_type: public_method
            serialized_name: Id
            accessor:
                getter: getId
                setter: setId
            xml_attribute: true
            type: string
