Digipost\Signature\API\XML\Thirdparty\XAdES\SigningTime:
    xml_root_name: SigningTime
    xml_root_namespace: 'http://uri.etsi.org/01903/v1.3.2#'
    properties:
        __value:
            expose: true
            xml_value: true
            access_type: public_method
            accessor:
                getter: value
                setter: value
            type: GoetasWebservices\Xsd\XsdToPhp\XMLSchema\DateTime
